---
  - hosts: all
    become: yes
    tasks:
    - name: Set Hostname
      ansible.builtin.hostname:
       name: "{{ inventory_hostname }}"
    - name: Update cache 
      apt:
       update_cache: yes
    - name: Install specified system packages
      apt:
        pkg:
          - jq
          - vim
        state: latest
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest
    - name: set timezone
      timezone:
        name: America/Chicago
