---
- hosts: jenkins
  become: yes
  tasks:
  - name: Import jenkins key from url
    ansible.builtin.apt_key:
      state: present
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

  - name: Download Long Term Jenkins release
    ansible.builtin.apt_repository:
      state: present
      repo: "deb https://pkg.jenkins.io/debian-stable binary/"

  - name: Update cache 
    apt:
      update_cache: yes     

  - name: Install java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started